services:
  - type: web
    name: nft-ticketing-hub
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://your-api-url.com
      - key: CI
        value: false
    healthCheckPath: /
    autoDeploy: true
    plan: free
    region: oregon
    nodeVersion: 16.18.0 